# Description: Definition of a StorageClass resource for dynamic storage in Amazon EBS.

apiVersion: storage.k8s.io/v1 # Kubernetes API version
kind: StorageClass # Resource type, in this case a storage class
metadata:
  name: mongodb-storage-class
provisioner: kubernetes.io/aws-ebs # Storage provider
reclaimPolicy: Retain # Storage reclaim policy
parameters:
  type: gp3 # EBS volume type
