# Description: Definition to create a Namespace in Kubernetes.

apiVersion: v1 # Kubernetes API version
kind: Namespace # Resource type, in this case a Namespace
metadata:
  # Name of the Namespace to create
  name: demo-k8s
