# Description: Definition of a Deployment resource to deploy a pod with MongoDB
#              and persistent storage at the node level with a host volume.

apiVersion: apps/v1 # Kubernetes API version
kind: Deployment # Resource type, in this case a Deployment
metadata:
  name: mongodb # Name of the Deployment
  namespace: demo-k8s # Namespace where the Deployment will be deployed

# Deployment specification.
spec:
  # Number of pod replicas to run.
  replicas: 1

  # Selector to identify the pods managed by this Deployment.
  selector:
    matchLabels:
      app: mongodb

  # Template for the pods created by this Deployment.
  template:
    metadata:
      labels:
        app: mongodb

    # Pod specification.
    spec:
      containers:
        - name: mongodb
          # Docker image to use for the MongoDB container.
          image: mongo:7.0.8-jammy
          # Port exposed by the MongoDB container.
          ports:
            - containerPort: 27017
          # Volume mount configuration for the MongoDB container.
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

      # Volume configuration for the pod.
      volumes:
        - name: mongo-storage
          # Host path volume configuration.
          hostPath:
            path: /mnt/data/mongodb
            type: DirectoryOrCreate
