# Description: Definition of a PersistentVolumeClaim (PVC) resource in Kubernetes
#              to request persistent storage on Amazon EBS

apiVersion: v1 # Kubernetes API version
kind: PersistentVolumeClaim # Resource type, in this case a PersistentVolumeClaim
metadata:
  name: mongodb-pvc-ebs # Name of the PVC
  namespace: demo-k8s # Namespace where the PVC will be created
# Specifications of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce # Read/Write access mode
  resources:
    requests:
      storage: 1Gi # Storage request of 1Gi
  selector:
    matchLabels:
      type: amazonEBS # Label to identify the type of storage
