# Description: Definition of a Deployment resource to deploy a pod with MongoDB.
#              This deployment uses a PersistentVolumeClaim (PVC) to provide persistent storage for MongoDB.

apiVersion: apps/v1 # Kubernetes API version
kind: Deployment # Resource type, in this case a Deployment
metadata:
  name: mongodb # Name of the Deployment
  namespace: demo-k8s # Namespace where the Deployment will be deployed
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: mongodb # Selector to identify the pods that belong to this Deployment
  template:
    metadata:
      labels:
        app: mongodb # Labels for the pods created by this Deployment
    spec:
      containers:
        - name: mongodb # Name of the container
          image: mongo:7.0.8-jammy # Docker image to be used for the container
          ports:
            - containerPort: 27017 # Port exposed by the container
          volumeMounts:
            - name: mongo-storage # Name of the mounted volume
              mountPath: /data/db # Path in the container where the volume will be mounted
      volumes:
        - name: mongo-storage # Name of the volume
          persistentVolumeClaim:
            claimName: mongodb-pvc-ebs # Name of the PersistentVolumeClaim to be used
