# Description: Definition of a PersistentVolume (PV) resource to provide
#              persistent storage using Amazon Elastic Block Store (EBS).

apiVersion: v1 # Kubernetes API version
kind: PersistentVolume # Resource type, in this case a PersistentVolume
metadata:
  name: mongodb-pv-ebs # Name of the PersistentVolume
  labels:
    type: amazonEBS # Label to identify the storage type
spec:
  capacity:
    storage: 1Gi # Storage capacity
  accessModes:
    - ReadWriteOnce # Access mode for read/write once
  awsElasticBlockStore:
    # EBS volume ID
    volumeID: aws://us-east-1b/vol-0bfdcf51c5e8bbaf7
    # File system type
    fsType: ext4
  # PersistentVolume reclaim policy
  persistentVolumeReclaimPolicy: Retain
