# Description: Definition of a PersistentVolumeClaim (PVC) resource for dynamic storage in Amazon EBS.

apiVersion: v1 # Kubernetes API version
kind: PersistentVolumeClaim # Resource type, in this case a PersistentVolumeClaim
metadata:
  name: mongodb-pvc-ebs # PVC name
  labels:
    type: amazonEBS # Label to identify the storage type
  namespace: demo-k8s # Namespace where the PVC will be created
# Specifications of the PersistentVolumeClaim
spec:
  storageClassName: mongodb-storage-class # Storage class to be used dynamically
  accessModes:
    - ReadWriteOnce # Access mode for read/write once
  resources:
    requests:
      storage: 1Gi # Storage request of 1Gi
