# Descripción:  Definición de un recurso tipo PersistentVolumeClaim (PVC) para almacenamiento dinámico en Amazon EBS.

apiVersion: v1 # Versión de la API de Kubernetes
kind: PersistentVolumeClaim # Tipo de recurso, en este caso un PersistentVolumeClaim
metadata:
  name: mongodb-pvc-ebs # Nombre del PVC
  labels:
    type: amazonEBS # Etiqueta para identificar el tipo de almacenamiento
  namespace: demo-k8s # Namespace donde se creará el PVC
# Especificaciones del PersistentVolumeClaim
spec:
  storageClassName: mongodb-storage-class # Clase de almacenamiento a utilizar de forma dinámica
  accessModes:
    - ReadWriteOnce # Modo de acceso de lectura/escritura única
  resources:
    requests:
      storage: 1Gi # Solicitud de almacenamiento de 1Gi
