# Description: Definition of a Deployment resource to deploy a pod
#              with a web application image in a Kubernetes cluster.

apiVersion: apps/v1 # Kubernetes API version
kind: Deployment # Resource type, in this case a Deployment
metadata:
  name: web-server # Name of the Deployment
  namespace: demo-k8s # Namespace where the Deployment will be created
spec:
  # Number of pod replicas
  replicas: 2
  selector:
    matchLabels:
      app: web-server # Label to identify the pod
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          # Container image
          image: oswaldeins/repo_unir:nodejs-app-v1.0
          # Ports exposed by the container
          ports:
            - containerPort: 3000
          # Environment variables
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/myDB?directConnection=true"
