# Description: Definition of a Service resource to expose
#              a web application in a Kubernetes cluster.

apiVersion: v1 # Kubernetes API version
kind: Service # Resource type, in this case a Service
metadata:
  name: web-server # Service name
  namespace: demo-k8s # Namespace where the Service will be created
# Service specifications
spec:
  # Service type, in this case a LoadBalancer
  type: LoadBalancer
  # Ports that the service will expose
  ports:
    - port: 3000 # Service port
      targetPort: 3000 # Pod port
  # Selector to identify the pods that this service will manage
  selector:
    app: web-server
